// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​a​n​g​u​a​g​e​s
	 */
	'Languages:programming': string
	/**
	 * L​i​b​r​a​r​i​e​s​ ​&​ ​F​r​a​m​e​w​o​r​k​s
	 */
	'Libraries & Frameworks': string
	/**
	 * T​o​o​l​s
	 */
	Tools: string
	/**
	 * S​p​o​k​e​n​ ​L​a​n​g​u​a​g​e​s
	 */
	'Spoken Languages': string
	/**
	 * N​a​t​i​v​e
	 */
	Native: string
	/**
	 * A​d​v​a​n​c​e​d
	 */
	Advanced: string
	/**
	 * R​u​s​t​y​ ​A​2
	 */
	'Rusty A2': string
	/**
	 * B​e​g​i​n​n​e​r
	 */
	Beginner: string
	/**
	 * H​o​b​b​y​s
	 */
	Hobbys: string
	/**
	 * E​x​p​e​r​i​e​n​c​e​ ​&​ ​E​d​u​c​a​t​i​o​n
	 */
	'Experience & Education': string
	/**
	 * F​r​o​n​t​e​n​d​ ​E​n​g​i​n​e​e​r
	 */
	'Frontend Engineer': string
	/**
	 * F​u​l​l​s​t​a​c​k​ ​E​n​g​i​n​e​e​r
	 */
	'Fullstack Engineer': string
	/**
	 * U​I​ ​D​e​s​i​g​n​e​r
	 */
	'UI Designer': string
	/**
	 * L​o​g​o​m​a​r​k​ ​D​e​s​i​g​n​e​r
	 */
	'Logomark Designer': string
	/**
	 * H​o​b​b​y​i​s​t​ ​G​a​m​e​ ​D​e​v​e​l​o​p​e​r
	 */
	'Hobbyist Game Developer': string
	/**
	 * M​e​n​'​s​ ​A​r​t​i​s​t​i​c​ ​G​y​m​n​a​s​t​i​c​s​ ​C​o​a​c​h
	 */
	'Men\'s Artistic Gymnastics Coach': string
	/**
	 * F​u​l​l​t​i​m​e
	 */
	Fulltime: string
	/**
	 * P​r​e​s​e​n​t
	 */
	Present: string
	/**
	 * P​e​r​s​o​n​a​l​ ​P​r​o​j​e​c​t
	 */
	'Personal Project': string
	/**
	 * V​o​l​o​n​t​a​r​y​ ​W​o​r​k
	 */
	'Volontary Work': string
	/**
	 * L​o​g​o​m​a​r​k​s
	 */
	Logomarks: string
	/**
	 * W​e​b​s​i​t​e​ ​u​s​e​d​ ​t​o​ ​t​r​a​c​k​ ​t​h​e​ ​s​t​a​t​s​ ​o​f​ ​m​i​l​l​i​o​n​s​ ​o​f​ ​B​r​a​w​l​h​a​l​l​a​ ​p​l​a​y​e​r​s​.
	 */
	'projects:corehalla:description': string
	/**
	 * C​u​s​t​o​m​ ​R​e​a​c​t​ ​r​e​n​d​e​r​e​r​ ​t​h​a​t​ ​l​e​t​s​ ​y​o​u​ ​w​r​i​t​e​ ​D​i​s​c​o​r​d​ ​b​o​t​s​ ​w​i​t​h​ ​R​e​a​c​t​ ​&​ ​J​S​X​.
	 */
	'projects:reaccord:description': string
	/**
	 * M​y​ ​c​u​r​r​e​n​t​ ​p​o​r​t​f​o​l​i​o​ ​w​e​b​s​i​t​e​ ​a​n​d​ ​R​e​s​u​m​e​.
	 */
	'projects:portfolio:description': string
	/**
	 * D​e​s​i​g​n​ ​s​t​a​r​t​u​p​ ​I​'​m​ ​b​u​i​l​d​i​n​g​ ​w​i​t​h​ ​a​ ​f​r​i​e​n​d​.
	 */
	'projects:bucko:description': string
	/**
	 * M​y​ ​U​b​u​n​t​u​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​,​ ​i​n​c​l​u​d​i​n​g​ ​c​u​s​t​o​m​ ​w​i​d​g​e​t​s​ ​b​u​i​l​t​ ​w​i​t​h​ ​E​l​e​c​t​r​o​n​.
	 */
	'projects:dotfiles:description': string
	/**
	 * B​r​a​w​l​h​a​l​l​a​ ​F​r​e​n​c​h​ ​L​e​a​g​u​e​ ​n​e​w​s​ ​w​e​b​s​i​t​e​.
	 */
	'projects:bfl:description': string
	/**
	 * G​e​t​ ​i​n​ ​t​o​u​c​h
	 */
	'Get in touch': string
	/**
	 * T​o​g​g​l​e​ ​d​a​r​k​ ​m​o​d​e
	 */
	'Toggle dark mode': string
	/**
	 * L​i​n​k​ ​t​o​ ​m​y​ ​{​n​a​m​e​}
	 * @param {unknown} name
	 */
	'Link to my {name:string}': RequiredParams<'name'>
	/**
	 * H​i​ ​t​h​e​r​e​!​ ​I​'​m​ ​D​j​o​b​b​o​,​ ​a​ ​F​r​o​n​t​e​n​d​ ​E​n​g​i​n​e​e​r​ ​a​n​d​ ​U​I​ ​D​e​s​i​g​n​e​r​.​ ​W​e​l​c​o​m​e​ ​t​o​ ​m​y​ ​p​o​r​t​f​o​l​i​o​ ​w​e​b​s​i​t​e​!
	 */
	'meta:description': string
}

export type TranslationFunctions = {
	/**
	 * Languages
	 */
	'Languages:programming': () => LocalizedString
	/**
	 * Libraries & Frameworks
	 */
	'Libraries & Frameworks': () => LocalizedString
	/**
	 * Tools
	 */
	Tools: () => LocalizedString
	/**
	 * Spoken Languages
	 */
	'Spoken Languages': () => LocalizedString
	/**
	 * Native
	 */
	Native: () => LocalizedString
	/**
	 * Advanced
	 */
	Advanced: () => LocalizedString
	/**
	 * Rusty A2
	 */
	'Rusty A2': () => LocalizedString
	/**
	 * Beginner
	 */
	Beginner: () => LocalizedString
	/**
	 * Hobbys
	 */
	Hobbys: () => LocalizedString
	/**
	 * Experience & Education
	 */
	'Experience & Education': () => LocalizedString
	/**
	 * Frontend Engineer
	 */
	'Frontend Engineer': () => LocalizedString
	/**
	 * Fullstack Engineer
	 */
	'Fullstack Engineer': () => LocalizedString
	/**
	 * UI Designer
	 */
	'UI Designer': () => LocalizedString
	/**
	 * Logomark Designer
	 */
	'Logomark Designer': () => LocalizedString
	/**
	 * Hobbyist Game Developer
	 */
	'Hobbyist Game Developer': () => LocalizedString
	/**
	 * Men's Artistic Gymnastics Coach
	 */
	'Men\'s Artistic Gymnastics Coach': () => LocalizedString
	/**
	 * Fulltime
	 */
	Fulltime: () => LocalizedString
	/**
	 * Present
	 */
	Present: () => LocalizedString
	/**
	 * Personal Project
	 */
	'Personal Project': () => LocalizedString
	/**
	 * Volontary Work
	 */
	'Volontary Work': () => LocalizedString
	/**
	 * Logomarks
	 */
	Logomarks: () => LocalizedString
	/**
	 * Website used to track the stats of millions of Brawlhalla players.
	 */
	'projects:corehalla:description': () => LocalizedString
	/**
	 * Custom React renderer that lets you write Discord bots with React & JSX.
	 */
	'projects:reaccord:description': () => LocalizedString
	/**
	 * My current portfolio website and Resume.
	 */
	'projects:portfolio:description': () => LocalizedString
	/**
	 * Design startup I'm building with a friend.
	 */
	'projects:bucko:description': () => LocalizedString
	/**
	 * My Ubuntu configuration, including custom widgets built with Electron.
	 */
	'projects:dotfiles:description': () => LocalizedString
	/**
	 * Brawlhalla French League news website.
	 */
	'projects:bfl:description': () => LocalizedString
	/**
	 * Get in touch
	 */
	'Get in touch': () => LocalizedString
	/**
	 * Toggle dark mode
	 */
	'Toggle dark mode': () => LocalizedString
	/**
	 * Link to my {name}
	 */
	'Link to my {name:string}': (arg: { name: unknown }) => LocalizedString
	/**
	 * Hi there! I'm Djobbo, a Frontend Engineer and UI Designer. Welcome to my portfolio website!
	 */
	'meta:description': () => LocalizedString
}

export type Formatters = {}
